name: college_scoreboard
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  http: ^1.2.0
  
  # Formatting
  intl: ^0.19.0
  
  # File Handling & Permissions (Fixes OpenFilex errors)
  open_filex: ^4.3.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  
  # Web Support (Fixes html.Blob, AnchorElement errors)
  universal_html: ^2.2.4
  
  # UI & Media
  video_player: ^2.10.1
  simple_animations: ^5.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/vp_logo.png
    - assets/cricket.png
    - assets/football.png
    - assets/volleyball.png
    - assets/kabaddi.jpeg
    - assets/vd.mp4
    - assets/carrom.jpg
    - assets/chess.jpg
    - assets/basketball.jpg